//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebapidbEntities : DbContext
    {
        public WebapidbEntities()
            : base("name=WebapidbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NgpContractor> NgpContractors { get; set; }
        public virtual DbSet<SampleLog> SampleLogs { get; set; }
        public virtual DbSet<SampleRole> SampleRoles { get; set; }
        public virtual DbSet<SampleTribe> SampleTribes { get; set; }
        public virtual DbSet<SampleUpload> SampleUploads { get; set; }
        public virtual DbSet<SampleUser> SampleUsers { get; set; }
    }
}
