//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngp_sched
    {
        public int schedID { get; set; }
        public string ors_no { get; set; }
        public string ors_date { get; set; }
        public string dv_no { get; set; }
        public string dv_date { get; set; }
        public string lddap_no { get; set; }
        public string lddap_date { get; set; }
        public Nullable<int> contractor_no { get; set; }
        public Nullable<int> contract_no { get; set; }
    
        public virtual ngp_contract ngp_contract { get; set; }
        public virtual ngp_contractor ngp_contractor { get; set; }
    }
}
